### PR TITLE
Fix network Watch tool causes Knots to crash and fix build for QT-5

### PR DESCRIPTION
**Pull request by AndyLavr**
View issues:

https://github.com/bitcoinknots/bitcoin/issues/4

### CODE REVIEW

**Comment by luke-jr** [comment]
This will cause it to not crash, but I'm afraid it doesn't look likely to actually fix the problem. :(

**Comment by AndyLavr** [comment]
There is no problem, everything works fine.

**Comment by luke-jr** [comment]
When `logpos` is non-zero, then appending to `log` is the wrong solution.

**Comment by AndyLavr** [comment]
And to fall and not work it right? You use DEBUG and ASSERT only locally for debugging.

**Comment by luke-jr** [comment]
If a situation which should be impossible exists, aborting is correct.

**Comment by AndyLavr** [comment]
I do not agree, I need to correct the error, and not annoy users of the fall of the program.

**Comment by luke-jr** [comment]
This patch does not correct the error, however.

**Comment by AndyLavr** [comment]
Well, so you added this feature? Yes? So you correct ... :)

**Comment by luke-jr** [comment]
If you're not going to actually try to find a fix, I'm closing this.

**Pull request closed without merging**
